# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    # Change the default password, please
    environment:
      POSTGRES_PASSWORD: spur_example_CHANGEME
    # Ports limited to localhost
    # Don't change this unless you know what you are doing securitywise
    ports:
      - 127.0.0.1:5432:5432
    volumes:
     - './data/postgresql:/var/lib/postgresql/data'

  # Stupid simple DB interface
  adminer:
    image: adminer
    restart: always
    # Ports limited to localhost
    # Don't change this unless you know what you are doing securitywise
    ports:
      - 127.0.0.1:8080:8080

  # PgAdmin is great, but can be a bit cumbersome
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 127.0.0.1:80:80
    environment:
      PGADMIN_DEFAULT_PASSWORD: spur_example_CHANGEME
      PGADMIN_DEFAULT_EMAIL: example@spur.us
